### ISSUE TITLE
Fails on JDK 13

### ISSUE THREAD

**Issue by janothan** [DanFaria/OAEI_SealsClient#2]
Evaluating a matching system fails with the following exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: eu/sealsproject/platform/res/tool/bundle/factory/PackageCreationException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: eu.sealsproject.platform.res.tool.bundle.factory.PackageCreationException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
```

Tested JDK:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

It works with JDK 1.8 but due to the nature of SEALS, this means that the matching system must also run with JDK 8.
